site_name: transcribo-backend
repo_url: https://github.com/DCC-BS/transcribo-backend
site_url: https://DCC-BS.github.io/transcribo-backend
site_description: The backend of the transcribo app
site_author: Data Competence Center Basel-Stadt
edit_uri: edit/main/docs/
repo_name: DCC-BS/transcribo-backend
copyright: Maintained by <a href="https://DCC-BS.com">Data Competence Center Basel-Stadt</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [
            "src/transcribo_backend"
            ]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DCC-BS/transcribo-backend
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/transcribo-backend

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
