"""Fetch Basel-specific hotwords from data.bs.ch into a cached asset file.

The asset is committed to the repo and loaded into the transcript-cleanup
agent's context at startup — this script does NOT run automatically. Re-run it
manually (or in a scheduled maintenance job) when the datasets change:

    make fetch-bs-context          # equivalent to --force
    uv run python scripts/fetch_hotwords.py [--force]

Sources:
    https://data.bs.ch/explore/dataset/100042/  (Wohnviertel)
    https://data.bs.ch/explore/dataset/100189/  (Strassennamen)
"""

import argparse
import sys
from pathlib import Path

import httpx

ASSET_PATH = Path(__file__).parent.parent / "src" / "transcribo_backend" / "assets" / "basel_hotwords.txt"

_BASE = "https://data.bs.ch/api/explore/v2.1/catalog/datasets/{dataset}/exports/json"

# dataset id -> field holding the term
_SOURCES = {
    "100042": "wov_name",
    "100189": "strassenname",
}


def _fetch_terms(client: httpx.Client, dataset: str, field: str) -> list[str]:
    response = client.get(_BASE.format(dataset=dataset), params={"select": field, "limit": -1})
    response.raise_for_status()
    terms = {str(row[field]).strip() for row in response.json() if row.get(field)}
    return sorted(terms)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true", help="overwrite an existing asset file")
    args = parser.parse_args()

    if ASSET_PATH.exists() and not args.force:
        print(f"{ASSET_PATH} already exists, use --force to refresh it.")
        return 0

    with httpx.Client(timeout=60) as client:
        sections: list[str] = [
            "# Basel hotwords (local proper names for transcript cleanup).",
            "# Generated by scripts/fetch_hotwords.py - do not edit manually.",
            "# Sources: data.bs.ch datasets 100042 (Wohnviertel), 100189 (Strassennamen).",
        ]
        for dataset, field in _SOURCES.items():
            terms = _fetch_terms(client, dataset, field)
            print(f"dataset {dataset}: {len(terms)} terms")
            sections.append("")
            sections.extend(terms)

    ASSET_PATH.parent.mkdir(parents=True, exist_ok=True)
    ASSET_PATH.write_text("\n".join(sections) + "\n", encoding="utf-8")
    print(f"wrote {ASSET_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
