name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-ci:
    uses: DCC-BS/ci-workflows/.github/workflows/python-backend-ci.yml@b522a713e5f9efc19b715d0d4938f37531db7f0d # v8.1
    with:
      python_versions: '["3.10","3.11","3.12","3.13"]'
      quality_python_version: "3.12"
      check_command: "make check"
